### ISSUE TITLE
validation runs even when email is blank

### ISSUE THREAD

**Issue by scootklein** [balexand/email_validator#25] opened 2015-02-06 19:45 UTC
Right now we have to split out validations to avoid 2 error messages. Consider the following:

```ruby
validates :email, presence: true, uniqueness: true, email: true
```

On a blank email submission, this will generate `["Email is blank", "Email is invalid"]` for the error messages. Creates a bit of confusion and generally isn't desirable for users. To avoid this, we have to split it out into 2 validations.

```ruby
validates :email, presence: true, uniqueness: true
validates :email, email: true, if: :email? # split out in case email is blank
```

Any chance we could add some smarts to only run the validation if email is present? I guess we could also drop the `presence: true` specifier, but then the error message won't be quite accurate ("blank" is more accurate than "invalid")

**Comment by balexand** [comment] 2015-02-09 18:22
I recommend splitting it out into 2 validations like you suggest. I prefer to use the `allow_blank` option ([see Rails Guide](http://guides.rubyonrails.org/active_record_validations.html#allow-blank)):

```ruby
validates :your_field, presence: true, uniqueness: true
validates :your_field, email: true, allow_blank: true
```

This behavior is consistent with the Rails built-in validators like, `format`, `inclusion`, `length`, `numericality`, etc. Those validators also generate errors when the field is blank.

**Comment by balexand** [comment] 2015-02-09 18:23
Duplicate of #9

**Closed by balexand** 2015-02-09 18:22 UTC
